# Writes src/zdd_gear.h, the gear table of design section 6.1: 256 values of
# SplitMix64 from seed 0x5a5a5a5a5a5a5a5a, each shifted right by one bit.
# The table is a format constant: once 0.1.0 is released it never changes,
# so this script must reproduce the committed header byte for byte
# (test-gear.R checks the values; `git diff` after running it checks the
# rest). Run from the package root:
#
#   Rscript tools/make-gear.R

source("tests/testthat/helper-bytes.R")

g <- gear_table()
rows <- vapply(seq(1, 256, by = 2), function(i) {
  sprintf("    UINT64_C(0x%s), UINT64_C(0x%s),", g[i], g[i + 1])
}, "")
rows[length(rows)] <- sub(",$", "", rows[length(rows)])

header <- c(
  "/*",
  " * zdd_gear.h -- THE FORMAT. Generated by tools/make-gear.R on 2026-10-08;",
  " * do not edit. Changing anything here changes every chunk boundary and",
  " * makes every existing store unreadable (design section 6).",
  " *",
  " * The gear table: G[i] = splitmix64_i(seed) >> 1 for i = 1..256, with",
  " * seed 0x5a5a5a5a5a5a5a5a. The shift keeps every entry below 2^63, so",
  " * (h >> 1) + G[b] never overflows 64 bits and an implementation with",
  " * unbounded integers (Python's fastcdc, the conformance oracle) computes",
  " * the same h.",
  " *",
  " * The boundary rule, which is as much the format as the table (design",
  " * section 6.2). For each chunk, h = 0 and n counts its bytes:",
  " *",
  " *   - the first `min` bytes are not hashed;",
  " *   - every later byte b: n += 1, h = (h >> 1) + G[b];",
  " *   - cut after it if (h & mask) == 0, where mask = MASK_S while",
  " *     n <= normal and MASK_L after;",
  " *   - cut at n == max regardless; the last chunk is what remains.",
  " *",
  " * With bits = log2(avg): MASK_S = 2^(bits + 1) - 1 and",
  " * MASK_L = 2^(bits - 1) - 1, contiguous low bits; for avg = 8 KiB they are",
  " * 0x3fff and 0x0fff. normal = avg - (min + ceil(min / 2)), floored at 0",
  " * and capped at max: the point where the stricter mask gives way, placed so",
  " * that the mean chunk size is close to avg. This is fastcdc 1.7.0's",
  " * cdc_offset() exactly (Python package, module fastcdc_py), with this",
  " * table in place of its GEAR.",
  " */",
  "#ifndef ZDD_GEAR_H",
  "#define ZDD_GEAR_H",
  "",
  "#include <stdint.h>",
  "",
  "#define ZDD_GEAR_SEED UINT64_C(0x5a5a5a5a5a5a5a5a)",
  "",
  "static const uint64_t zdd_gear[256] = {",
  rows,
  "};",
  "",
  "#endif"
)
writeLines(header, "src/zdd_gear.h")
