/*
 * zdd_gear.h -- THE FORMAT. Generated by tools/make-gear.R on 2026-10-08;
 * do not edit. Changing anything here changes every chunk boundary and
 * makes every existing store unreadable (design section 6).
 *
 * The gear table: G[i] = splitmix64_i(seed) >> 1 for i = 1..256, with
 * seed 0x5a5a5a5a5a5a5a5a. The shift keeps every entry below 2^63, so
 * (h >> 1) + G[b] never overflows 64 bits and an implementation with
 * unbounded integers (Python's fastcdc, the conformance oracle) computes
 * the same h.
 *
 * The boundary rule, which is as much the format as the table (design
 * section 6.2). For each chunk, h = 0 and n counts its bytes:
 *
 *   - the first `min` bytes are not hashed;
 *   - every later byte b: n += 1, h = (h >> 1) + G[b];
 *   - cut after it if (h & mask) == 0, where mask = MASK_S while
 *     n <= normal and MASK_L after;
 *   - cut at n == max regardless; the last chunk is what remains.
 *
 * With bits = log2(avg): MASK_S = 2^(bits + 1) - 1 and
 * MASK_L = 2^(bits - 1) - 1, contiguous low bits; for avg = 8 KiB they are
 * 0x3fff and 0x0fff. normal = avg - (min + ceil(min / 2)), floored at 0
 * and capped at max: the point where the stricter mask gives way, placed so
 * that the mean chunk size is close to avg. This is fastcdc 1.7.0's
 * cdc_offset() exactly (Python package, module fastcdc_py), with this
 * table in place of its GEAR.
 */
#ifndef ZDD_GEAR_H
#define ZDD_GEAR_H

#include <stdint.h>

#define ZDD_GEAR_SEED UINT64_C(0x5a5a5a5a5a5a5a5a)

static const uint64_t zdd_gear[256] = {
    UINT64_C(0x2523b5abda0acc23), UINT64_C(0x642d7e1c20d41ef3),
    UINT64_C(0x3d1973b7b977f576), UINT64_C(0x4c82b27344fd0e06),
    UINT64_C(0x7d045dd074d49cb2), UINT64_C(0x174a7d07e5388236),
    UINT64_C(0x51a6357b60924070), UINT64_C(0x5e4f5dc3b59a1ed6),
    UINT64_C(0x144dad3bbc532b78), UINT64_C(0x3e2e07c5f7945380),
    UINT64_C(0x13472e9c6fb35a8a), UINT64_C(0x1eb9fae26fb6fbf3),
    UINT64_C(0x1a56d06775e46e28), UINT64_C(0x71ff2054a7584eaf),
    UINT64_C(0x6c44966ff7fbec66), UINT64_C(0x6e1cd4057f90e8b0),
    UINT64_C(0x6fe4634281366736), UINT64_C(0x2c34312c606ced4b),
    UINT64_C(0x3c9b85e161e85924), UINT64_C(0x7e8af76bbde9f47f),
    UINT64_C(0x2af756b5dd2d9fe7), UINT64_C(0x662109d0dad70d1f),
    UINT64_C(0x7aca7de56076fe45), UINT64_C(0x216cdc8a295537ac),
    UINT64_C(0x7aab7950ae2cc722), UINT64_C(0x565bcb83ee94245a),
    UINT64_C(0x4dd37c93876f569e), UINT64_C(0x35308cbd38543914),
    UINT64_C(0x4e653118fe80f664), UINT64_C(0x7c8174c67185f13c),
    UINT64_C(0x6101a8babe6701e9), UINT64_C(0x16ec76e0acc59380),
    UINT64_C(0x2a7755ea644eb369), UINT64_C(0x113d059efe872852),
    UINT64_C(0x5f121a7300651d7a), UINT64_C(0x1c4418e36cc71a12),
    UINT64_C(0x2a4f8c9478d93cc7), UINT64_C(0x720cd31a3190b88f),
    UINT64_C(0x322ae86843be7c20), UINT64_C(0x23ea8c44272f0f57),
    UINT64_C(0x7bef92961a7e2a42), UINT64_C(0x0d387c426cacb1a6),
    UINT64_C(0x190c1e31759eaed0), UINT64_C(0x27dc55f446932b79),
    UINT64_C(0x5cfe7f1b9b0ff63a), UINT64_C(0x2244d4710f14d386),
    UINT64_C(0x2638083b369d5b7a), UINT64_C(0x3a34e92caf107a15),
    UINT64_C(0x6a392581e6ae2a82), UINT64_C(0x22d9d93b6b6a2ff8),
    UINT64_C(0x2c3785849a6abe68), UINT64_C(0x5477b86d9c08e37d),
    UINT64_C(0x33e142091ab79845), UINT64_C(0x0c9b51ee3ff3ad1f),
    UINT64_C(0x113cae70cb7cb986), UINT64_C(0x1d762148d41e578d),
    UINT64_C(0x7b4634a9cfb9af19), UINT64_C(0x5fbe8d8d3468e0b6),
    UINT64_C(0x23e16add2fc72660), UINT64_C(0x1c3cdfdfba35d3dc),
    UINT64_C(0x40539496c953c402), UINT64_C(0x791e70d0828845ec),
    UINT64_C(0x78b2be4bc58798c7), UINT64_C(0x493277fa6ffd41e4),
    UINT64_C(0x10098d748c29ffa3), UINT64_C(0x1c7211d29b9915cd),
    UINT64_C(0x4de43ba844c89aeb), UINT64_C(0x0b70afae80106fa4),
    UINT64_C(0x12567b3b7331f635), UINT64_C(0x2c0dda6d3f0ef84d),
    UINT64_C(0x74dd67e00b049720), UINT64_C(0x7ac14e85a1e68b3a),
    UINT64_C(0x07efd744ae014d9c), UINT64_C(0x39e2d7fd54b48355),
    UINT64_C(0x28f3b90bbfcfdfc4), UINT64_C(0x521af8265b19ece7),
    UINT64_C(0x3272403f4fc4b2a3), UINT64_C(0x6b858283195c001d),
    UINT64_C(0x7b874e23afe3e40f), UINT64_C(0x586b10c8a759cee0),
    UINT64_C(0x7bbec129a493e19d), UINT64_C(0x5e1cc2e7a28be7f4),
    UINT64_C(0x76e24fa60ea259ef), UINT64_C(0x273b773b17948086),
    UINT64_C(0x3a42a1ab67fdde74), UINT64_C(0x26aa8cf924c07706),
    UINT64_C(0x3cde1396426fdb3d), UINT64_C(0x2f07c9ea162321f0),
    UINT64_C(0x71fee7b4c37f4fc9), UINT64_C(0x2ec8da2b28cef731),
    UINT64_C(0x3f1fed599de2d898), UINT64_C(0x243de31eb6c2c0fd),
    UINT64_C(0x050254313b58d356), UINT64_C(0x36a9d63217bc225e),
    UINT64_C(0x22c1f2224ee70374), UINT64_C(0x0c746f10821402d7),
    UINT64_C(0x7b31f65a05ea46fc), UINT64_C(0x73cf089fc6a0edf6),
    UINT64_C(0x7762558e9b94f4c6), UINT64_C(0x00307b3513668157),
    UINT64_C(0x127a43933ab2d54d), UINT64_C(0x6e60446de28bdf7d),
    UINT64_C(0x02b71389ba14b689), UINT64_C(0x7f584791fd99d311),
    UINT64_C(0x6305f37ab7765109), UINT64_C(0x74100cfaa65b0322),
    UINT64_C(0x5ac296af7435caf3), UINT64_C(0x32f1a12298db9394),
    UINT64_C(0x68743445e22816f1), UINT64_C(0x2d1d014cce340ce6),
    UINT64_C(0x619adddd59e68df2), UINT64_C(0x360f0b8045687fe1),
    UINT64_C(0x6e13f9cf380ea386), UINT64_C(0x0960d576ee514bde),
    UINT64_C(0x698e5a448c434ce9), UINT64_C(0x58e1af8d9e2068ca),
    UINT64_C(0x64b8eaf9847ac343), UINT64_C(0x0d2828214ac11e7a),
    UINT64_C(0x6abbae8ed9f56a4a), UINT64_C(0x0598f84ea94fdebc),
    UINT64_C(0x220b02d7a8ed2766), UINT64_C(0x0d8455484d99a07d),
    UINT64_C(0x336e01e8419ab82b), UINT64_C(0x06c10f1456d8d5b0),
    UINT64_C(0x6a2390b096df68eb), UINT64_C(0x5c77666363620f5f),
    UINT64_C(0x46c1a5aba449c968), UINT64_C(0x1d08ce5bba0adfab),
    UINT64_C(0x4517263b67ad2b5e), UINT64_C(0x7f4dc6d920545d4a),
    UINT64_C(0x5e60ba05ca4f5c79), UINT64_C(0x292c4213a87a5afb),
    UINT64_C(0x4b57bc03cef4b1f5), UINT64_C(0x75cee74b37469f14),
    UINT64_C(0x77c98b7916dd8a62), UINT64_C(0x3faad44587d215b1),
    UINT64_C(0x0343c47e043b40a8), UINT64_C(0x6685e4c8134c3dfc),
    UINT64_C(0x7a6d374bd42abd9c), UINT64_C(0x65c9a0205cdd4b44),
    UINT64_C(0x2807d61f3ffa7a41), UINT64_C(0x6bfd518e7753f09d),
    UINT64_C(0x63eb67baff0a8e05), UINT64_C(0x0f2175a4292ab3a8),
    UINT64_C(0x49fac33988957467), UINT64_C(0x15a4921fce157c80),
    UINT64_C(0x7c7042ddbb402c4e), UINT64_C(0x3e4d18d34edf8b89),
    UINT64_C(0x592ebd6689659e4a), UINT64_C(0x003418fdced903fa),
    UINT64_C(0x443fb9bdd6d6260c), UINT64_C(0x6ab24b9f30536e61),
    UINT64_C(0x07608824c1106926), UINT64_C(0x72d65bbc34bbc386),
    UINT64_C(0x15e335393a68a727), UINT64_C(0x3ea96e26a4b8b0c0),
    UINT64_C(0x7d8d9a83292ce265), UINT64_C(0x1602b785fb602cd6),
    UINT64_C(0x54e55071ef1bc985), UINT64_C(0x27ddadf5f6fb643b),
    UINT64_C(0x31d9bfea211e0452), UINT64_C(0x6c413f7a695394cd),
    UINT64_C(0x5d6dfbed8c2eedd9), UINT64_C(0x2e358cb673d1124e),
    UINT64_C(0x55bed3e2fb24dbb8), UINT64_C(0x4d232cd59f32e919),
    UINT64_C(0x2da62dc8941ac608), UINT64_C(0x4d3fb756f02b67f5),
    UINT64_C(0x266b5d3c6a8afec7), UINT64_C(0x6a19dc2b4de87515),
    UINT64_C(0x187a1b760f76b3a9), UINT64_C(0x073d5f524a4da18e),
    UINT64_C(0x636eaf4394c04118), UINT64_C(0x6e74522b70d3246a),
    UINT64_C(0x7e96525a5448a722), UINT64_C(0x11b69bc4c698afd3),
    UINT64_C(0x26b764852f0c1a2b), UINT64_C(0x1fd70af2119b49e7),
    UINT64_C(0x00536207619e4fbd), UINT64_C(0x06b2194ca114724e),
    UINT64_C(0x1f491f3f1526d7fb), UINT64_C(0x64a35fa34094e468),
    UINT64_C(0x044039c1dd84c883), UINT64_C(0x6718d4193eb5e7c3),
    UINT64_C(0x417543245112ec5f), UINT64_C(0x50d346384fa2fb73),
    UINT64_C(0x54f0184fbd4e3d12), UINT64_C(0x7641d4040c51451c),
    UINT64_C(0x27871c6f2de469ce), UINT64_C(0x579d818c3769f97a),
    UINT64_C(0x740b50a730826e3a), UINT64_C(0x4beaaa127865c1cd),
    UINT64_C(0x3cc397da60d22904), UINT64_C(0x7244c0515fccafec),
    UINT64_C(0x664c082c770a1243), UINT64_C(0x37a7692f09d89fe9),
    UINT64_C(0x52dfbc73614a03c0), UINT64_C(0x6781981bfee28c6c),
    UINT64_C(0x383ec0c30c2cec6d), UINT64_C(0x300eebb1351fbf1d),
    UINT64_C(0x035c02e41116671d), UINT64_C(0x75e37ec384c9e36f),
    UINT64_C(0x42a0a9abea0f83a2), UINT64_C(0x111b94b6645eb345),
    UINT64_C(0x085170d8002816d4), UINT64_C(0x52246e945fea92be),
    UINT64_C(0x06f1babc1959e753), UINT64_C(0x17ef30211098b35d),
    UINT64_C(0x196539c788c694db), UINT64_C(0x09fb29cfc9d04186),
    UINT64_C(0x3eb3abf62675c4bf), UINT64_C(0x51412e188315c874),
    UINT64_C(0x6fc8dc677efc36ca), UINT64_C(0x2d34f45a806c2bce),
    UINT64_C(0x26218a199a2b21bf), UINT64_C(0x5d63fb85fdcacbc4),
    UINT64_C(0x7cdb948dd614ee16), UINT64_C(0x69adad3f65964e62),
    UINT64_C(0x3051729960ce40b8), UINT64_C(0x5588f84649561422),
    UINT64_C(0x64e13efa1d998a7c), UINT64_C(0x3a48037739b8f7b7),
    UINT64_C(0x1afd2376b91e8a30), UINT64_C(0x5b4d9e46b05c53d5),
    UINT64_C(0x2f9543e982d3cda1), UINT64_C(0x1695ddcaf9b4c486),
    UINT64_C(0x2a0c34160b36b832), UINT64_C(0x6f6ecab143f233ed),
    UINT64_C(0x69826a1f94a67b8d), UINT64_C(0x340b206d9b1ff43c),
    UINT64_C(0x79b8b30baed336dd), UINT64_C(0x694dfb7d17f74ab5),
    UINT64_C(0x6d15a678143a4ee6), UINT64_C(0x267d72840700ea23),
    UINT64_C(0x54b855498f95aab6), UINT64_C(0x4e775f4f0fb7db5f),
    UINT64_C(0x4fd38dca6b58feaa), UINT64_C(0x5ec2ffe765f76994),
    UINT64_C(0x0b71bc8e18d79ea7), UINT64_C(0x30b6204b5cf56252),
    UINT64_C(0x50b332ee8825b77e), UINT64_C(0x5f487c64cce8fc22),
    UINT64_C(0x272cf3c27b241cc0), UINT64_C(0x1641b3e7e37d9545),
    UINT64_C(0x1d9438cba1354f87), UINT64_C(0x73ccc23eaeb32a0c),
    UINT64_C(0x07f6e43b88fddc81), UINT64_C(0x58a929be00f6372c),
    UINT64_C(0x1bb5de71b79af6d5), UINT64_C(0x3d18e008e4fcf6fc),
    UINT64_C(0x4a59efe822ae454a), UINT64_C(0x42bc0c0cfd55baad),
    UINT64_C(0x6b589a630a71641c), UINT64_C(0x30ad13b3fe2f7c76),
    UINT64_C(0x7bf1b4ad5d7daed1), UINT64_C(0x28d9f364b1947e38)
};

#endif
